version: "3.9"  # optional since v1.27.0
services:
  # PRODUCTION
  prod-post-handler:
    restart: unless-stopped
    image: post-handler:local
    ports:
      - "8080:8080"
    environment:
      - AUTH_USERNAME=test
      - AUTH_PASSWORD=test
      - SMB_ENABLED=false
    networks:
      - post-handler

networks:
  post-handler:
    driver: bridge
  post-requester:
    driver: bridge